/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author uillia
 */
public class TelaMenu extends javax.swing.JFrame {

    /** Creates new form TelaMenu */
    public TelaMenu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuEmpresa = new javax.swing.JMenu();
        menuItemFunc = new javax.swing.JMenuItem();
        menuItemCadVeiculos = new javax.swing.JMenuItem();
        menuItemAltVeiculos = new javax.swing.JMenuItem();
        menuItemLoc = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        menuItemCadCli = new javax.swing.JMenuItem();
        menuItemConsLoc = new javax.swing.JMenuItem();
        menuItemDevolucao = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuEmpresa.setText("Empresa");

        menuItemFunc.setText("Cadastrar Funcionário");
        menuItemFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFuncActionPerformed(evt);
            }
        });
        menuEmpresa.add(menuItemFunc);

        menuItemCadVeiculos.setText("Cadastrar Veículos");
        menuItemCadVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadVeiculosActionPerformed(evt);
            }
        });
        menuEmpresa.add(menuItemCadVeiculos);

        menuItemAltVeiculos.setText("Alterar Veículos");
        menuItemAltVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAltVeiculosActionPerformed(evt);
            }
        });
        menuEmpresa.add(menuItemAltVeiculos);

        menuItemLoc.setText("Realizar Locação");
        menuItemLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLocActionPerformed(evt);
            }
        });
        menuEmpresa.add(menuItemLoc);

        jMenuBar1.add(menuEmpresa);

        menuCliente.setText("Cliente");

        menuItemCadCli.setText("Cadastrar Cliente");
        menuItemCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadCliActionPerformed(evt);
            }
        });
        menuCliente.add(menuItemCadCli);

        menuItemConsLoc.setText("Consultar Locação");
        menuItemConsLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsLocActionPerformed(evt);
            }
        });
        menuCliente.add(menuItemConsLoc);

        menuItemDevolucao.setText("Realizar Devolução");
        menuItemDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDevolucaoActionPerformed(evt);
            }
        });
        menuCliente.add(menuItemDevolucao);

        jMenuBar1.add(menuCliente);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFuncActionPerformed
        dispose();
        TelacadFunc t = new TelacadFunc();
        t.setVisible(true);
    }//GEN-LAST:event_menuItemFuncActionPerformed

    private void menuItemCadVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadVeiculosActionPerformed
        dispose();
        TelacadVeiculo t = new TelacadVeiculo();
        t.setVisible(true);
    }//GEN-LAST:event_menuItemCadVeiculosActionPerformed

    private void menuItemAltVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAltVeiculosActionPerformed
        dispose();
        TelaAlterarVeiculo t = new TelaAlterarVeiculo();
        t.setVisible(true);
    }//GEN-LAST:event_menuItemAltVeiculosActionPerformed

    private void menuItemLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLocActionPerformed
        dispose();
        TelaLocacao t = new TelaLocacao();
        t.setVisible(true);
    }//GEN-LAST:event_menuItemLocActionPerformed

    private void menuItemCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadCliActionPerformed
        dispose();
        TelacadCli t = new TelacadCli();
        t.setVisible(true);
    }//GEN-LAST:event_menuItemCadCliActionPerformed

    private void menuItemConsLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsLocActionPerformed
        dispose();
        TelaConsultaLoc t = new TelaConsultaLoc();
        t.setVisible(true);
    }//GEN-LAST:event_menuItemConsLocActionPerformed

    private void menuItemDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDevolucaoActionPerformed
        dispose();
        TelaDevolucao t = new TelaDevolucao();
        t.setVisible(true);
    }//GEN-LAST:event_menuItemDevolucaoActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuEmpresa;
    private javax.swing.JMenuItem menuItemAltVeiculos;
    private javax.swing.JMenuItem menuItemCadCli;
    private javax.swing.JMenuItem menuItemCadVeiculos;
    private javax.swing.JMenuItem menuItemConsLoc;
    private javax.swing.JMenuItem menuItemDevolucao;
    private javax.swing.JMenuItem menuItemFunc;
    private javax.swing.JMenuItem menuItemLoc;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables

}
